ERROR_RESPONSE_CODES = {
    'INPUT_VALIDATION_FAILURE': 'INPUT_VALIDATION_FAILURE',
    'RESPONSE_VALIDATION_FAILURE': 'RESPONSE_VALIDATION_FAILURE',
    'EXTERNAL_API_FAILURE': 'EXTERNAL_API_FAILURE',
    'DATABASE_FAILURE': 'DATABASE_FAILURE'
}

SYMBOL_TOKEN_MAPPING = {
    '11184': 'idfc_first_bank'
}