version: '3.8'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/home/ml/Desktop/projects/mysql_data:/var/lib/mysql
      - /var/run/mysqld:/var/run/mysqld
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql8:db
    ports:
      - "8888:80"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ~/home/ml/Desktop/projects/influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"


  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --bind 0.0.0.0
    volumes:
      - ~/home/ml/Desktop/projects/redis_data:/financial_data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - static:/app/staticfiles
    restart: always
    ports:
      - "8000:8000"

#  celery:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: celery_container
#    command: celery -A celery_app worker -l info
#    depends_on:
#      - redis
#      - mysql8
#
#  celery-beat:
#    build:
#      context: .
#      dockerfile: ./Dockerfile
#    container_name: celery_beat_container
#    command: celery -A celery_app beat -l info
##    volumes:
##      - ./trade_smart_backend:/trade_smart
#    depends_on:
#      - redis
#      - mysql8