version: '3.8'
services:
  mysql8:
    image: mysql:8
    container_name: mysql8
    environment:
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - ~/home/ml/Desktop/projects/mysql_data:/var/lib/mysql
      - /var/run/mysqld:/var/run/mysqld
    ports:
      - "3306:3306"

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    links:
      - mysql8:db
    ports:
      - "8888:80"

  influxdb:
    image: influxdb:latest
    container_name: influxdb
    volumes:
      - ~/home/ml/Desktop/projects/influxdb_data:/var/lib/influxdb
    ports:
      - "8086:8086"


  redis:
    image: redis:latest
    container_name: redis
    command: redis-server --bind 0.0.0.0
    volumes:
      - ~/home/ml/Desktop/projects/redis_data:/financial_data
    ports:
      - "6379:6379"

  web:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: web
    command: /bin/bash -c "/usr/local/bin/supervisord -n -c /etc/supervisord.d/web.conf"
    ports:
      - "80:80"
    depends_on:
      - redis
      - mysql8

  worker:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: worker
    command: /bin/bash -c "/usr/local/bin/supervisord -n -c /etc/supervisord.d/worker.conf"
    depends_on:
      - redis
      - mysql8

  beat:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: beat
    command: /bin/bash -c "/usr/local/bin/supervisord -n -c /etc/supervisord.d/beat.conf"
    depends_on:
      - redis
      - mysql8

  flower:
    build:
      context: .
      dockerfile: ./Dockerfile
      network: host
    container_name: flower
    command: /bin/bash -c "/usr/local/bin/supervisord -n -c /etc/supervisord.d/flower.conf"
    depends_on:
      - redis
      - mysql8
