"""
Django settings for trade_smart_backend project.

Generated by 'django-admin startproject' using Django 4.2.3.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""
import os
from .secret import SECRET_MANAGER_CONFIG
from pathlib import Path
# Build paths inside the project like this: BASE_DIR / 'subdir'.
PROJECT_ROOT = os.path.dirname((os.path.abspath(__file__)))
PROJECT_DIR = os.path.dirname(PROJECT_ROOT)
BASE_DIR = os.path.dirname(PROJECT_DIR)
# BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-v6b8nc0$ad0c5(h55zb9yj8oi=gm7bx(3&czjv=80modss#6by'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ["*"]


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles'
    # 'trade_smart_backend.apps.analyse',
    # 'trade_smart_backend.apps.data',
    # 'trade_smart_backend.apps.strategy',
    # 'trade_smart_backend.apps.trade'
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'trade_smart_backend.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [os.path.join(BASE_DIR, 'trade_smart_backend/trade_smart_backend/templates')],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'trade_smart_backend.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
#     dev
    'default': {
        'ENGINE': 'django.db.backends.mysql',
        'NAME': 'trade_smart',
        'USER': 'trade_smart_root',
        'PASSWORD': 'trade_smart_root',
        'HOST': 'localhost',
        'POST': 3306
    }
}

INFLUX_DATABASE = {
    'CONNECT': {
        'host': 'localhost',
        'port':8086,
        'username': 'nodered',
        'password': 'nodered'
    },
    'DATABASE': {
        'nse_stocks': 'nse_stocks',
        'nse_indicators': 'nse_indicators'
    }
}

# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/
STATIC_ROOT =  os.path.join(BASE_DIR, 'trade_smart_backend/static')
STATIC_URL = '/static/'

STATICFILES_FINDERS = {
    'django.contrib.staticfiles.finders.FileSystemFinder',
    'django.contrib.staticfiles.finders.AppDirectoriesFinder'
}

# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

STATICFILES_DIRS = [
    os.path.join(BASE_DIR, 'trade_smart_backend', 'trade_smart_backend', 'static')
]


BASE_URL = 'https://apiconnect.angelbroking.com'
TRADE_API_KEY = SECRET_MANAGER_CONFIG.get("TRADE_API_KEY", "")
DATA_1_API_KEY = SECRET_MANAGER_CONFIG.get("DATA_1_API_KEY", "")
TRADE_SECRET_KEY = SECRET_MANAGER_CONFIG.get("TRADE_SECRET_KEY", "")
CLIENT_ID = SECRET_MANAGER_CONFIG.get("CLIENT_ID", "")
CLIENT_PASSWORD = SECRET_MANAGER_CONFIG.get("CLIENT_PASSWORD", "")